name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Labo0

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Créer fichier .env 
        run: |
          echo "CALCULATOR_USERNAME=GithubActions" >> .env

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Éxécuter les tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: | 
          python -m pytest
